general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  parser_opacity: 80
maps:
  auto_follow: true
  geometry:
  - 1620
  - 567
  - 276
  - 356
  grid_line_width: 1
  last_zone: ak'anon
  line_width: 1
  scale: 0.07487642513951304
  show_poi: true
  toggled: true
spells:
  casting_window_buffer: 1000
  delay_self_buffs_on_zone: true
  geometry:
  - 1610
  - 35
  - 292
  - 522
  level: 6
  toggled: true
  use_casting_window: true
  use_secondary:
  - levitate
  use_secondary_all: false
