general:
  eq_log_dir: ''
  update_interval_msec: 250
maps:
  grid_line_width: 1
  last_zone: East Commonlands
  line_width: 1
  scale: 0.05
  show_poi: true
  toggled: true
spells:
  level: 1
  seconds_offset: 0
  toggled: true
