general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  parser_opacity: 80
  qt_scale_factor: 100
maps:
  auto_follow: true
  closest_z_alpha: 20
  current_z_alpha: 100
  geometry:
  - 1396
  - 65
  - 449
  - 200
  grid_line_width: 1
  last_zone: erud's crossing
  line_width: 1
  other_z_alpha: 10
  scale: 0.18393538451270866
  show_grid: true
  show_poi: true
  toggled: true
  use_z_layers: false
spells:
  casting_window_buffer: 1000
  delay_self_buffs_on_zone: true
  geometry:
  - 218
  - 91
  - 285
  - 887
  level: 8
  toggled: true
  use_casting_window: true
  use_instants: true
  use_secondary:
  - levitate
  use_secondary_all: false
