general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  update_interval_msec: 250
maps:
  geometry:
  - 1963
  - 277
  - 250
  - 720
  grid_line_width: 1
  last_zone: erud's crossing
  line_width: 1
  scale: 0.08296251592302355
  show_poi: true
  toggled: true
spells:
  geometry:
  - 1954
  - 106
  - 208
  - 112
  level: 1
  seconds_offset: 0
  toggled: true
