general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  parser_opacity: 80
  qt_scale_factor: 100
maps:
  auto_follow: true
  closest_z_alpha: 20
  current_z_alpha: 100
  geometry:
  - 1159
  - 420
  - 449
  - 396
  grid_line_width: 1
  last_zone: ruins of old guk
  line_width: 1
  other_z_alpha: 5
  scale: 0.4826607518990071
  show_grid: true
  show_poi: true
  toggled: true
  use_z_layers: true
spells:
  casting_window_buffer: 1000
  delay_self_buffs_on_zone: true
  geometry:
  - 501
  - 108
  - 310
  - 993
  level: 51
  toggled: false
  use_casting_window: true
  use_secondary:
  - levitate
  use_secondary_all: false
