general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  update_interval_msec: 250
maps:
  auto_follow: true
  geometry:
  - 3494
  - 274
  - 349
  - 238
  grid_line_width: 1
  last_zone: Lavastorm Mountains
  line_width: 1
  scale: 0.10742858301372651
  show_poi: true
  toggled: true
spells:
  geometry:
  - 3546
  - 60
  - 208
  - 208
  level: 51
  seconds_offset: 0
  toggled: true
  use_secondary:
  - levitate
  use_secondary_all: false
