general:
  eq_log_dir: F:/EverQuest Project 1999/Logs
  update_interval_msec: 250
maps:
  geometry:
  - 1974
  - 66
  - 250
  - 160
  grid_line_width: 1
  last_zone: East Commonlands
  line_width: 1
  scale: 0.05
  show_poi: false
  toggled: true
spells:
  geometry:
  - 2011
  - 245
  - 208
  - 112
  level: 1
  seconds_offset: 0
  toggled: true
