general:
  eq_log_dir: ''
  parser_opacity: 80
  qt_scale_factor: 100
maps:
  auto_follow: true
  closest_z_alpha: 20
  current_z_alpha: 100
  geometry:
  - 301
  - 100
  - 200
  - 200
  grid_line_width: 1
  last_zone: east commonlands
  line_width: 1
  other_z_alpha: 10
  scale: 0.021398563121912056
  show_grid: true
  show_poi: true
  toggled: true
  use_z_layers: false
spells:
  casting_window_buffer: 1000
  delay_self_buffs_on_zone: true
  geometry:
  - 100
  - 100
  - 200
  - 200
  level: 1
  toggled: true
  use_casting_window: true
  use_secondary:
  - levitate
  use_secondary_all: false
